// Lista de aeroportos para os campos de origem/destino de Passagens Aéreas.
// Formato do valor gravado: "IATA - Cidade/UF (ou País)" — texto livre continua aceito,
// já que registros antigos/importados podem ter qualquer string.

export interface Aeroporto {
  iata: string;
  nome: string;
  cidade: string;
  pais: string;
}

export const AEROPORTOS: Aeroporto[] = [
  // ── Brasil ────────────────────────────────────────────────────────────────
  { iata: "GRU", nome: "Guarulhos – Gov. André Franco Montoro", cidade: "São Paulo/SP", pais: "Brasil" },
  { iata: "CGH", nome: "Congonhas", cidade: "São Paulo/SP", pais: "Brasil" },
  { iata: "VCP", nome: "Viracopos", cidade: "Campinas/SP", pais: "Brasil" },
  { iata: "GIG", nome: "Galeão – Antônio Carlos Jobim", cidade: "Rio de Janeiro/RJ", pais: "Brasil" },
  { iata: "SDU", nome: "Santos Dumont", cidade: "Rio de Janeiro/RJ", pais: "Brasil" },
  { iata: "MEA", nome: "Macaé", cidade: "Macaé/RJ", pais: "Brasil" },
  { iata: "CFB", nome: "Cabo Frio", cidade: "Cabo Frio/RJ", pais: "Brasil" },
  { iata: "CAW", nome: "Bartolomeu Lysandro", cidade: "Campos dos Goytacazes/RJ", pais: "Brasil" },
  { iata: "BSB", nome: "Presidente Juscelino Kubitschek", cidade: "Brasília/DF", pais: "Brasil" },
  { iata: "CNF", nome: "Tancredo Neves – Confins", cidade: "Belo Horizonte/MG", pais: "Brasil" },
  { iata: "PLU", nome: "Pampulha", cidade: "Belo Horizonte/MG", pais: "Brasil" },
  { iata: "UDI", nome: "Ten. Cel. Av. César Bombonato", cidade: "Uberlândia/MG", pais: "Brasil" },
  { iata: "UBA", nome: "Mário de Almeida Franco", cidade: "Uberaba/MG", pais: "Brasil" },
  { iata: "JDF", nome: "Francisco de Assis", cidade: "Juiz de Fora/MG", pais: "Brasil" },
  { iata: "IPN", nome: "Usiminas", cidade: "Ipatinga/MG", pais: "Brasil" },
  { iata: "MOC", nome: "Mário Ribeiro", cidade: "Montes Claros/MG", pais: "Brasil" },
  { iata: "POA", nome: "Salgado Filho", cidade: "Porto Alegre/RS", pais: "Brasil" },
  { iata: "CXJ", nome: "Hugo Cantergiani", cidade: "Caxias do Sul/RS", pais: "Brasil" },
  { iata: "PET", nome: "João Simões Lopes Neto", cidade: "Pelotas/RS", pais: "Brasil" },
  { iata: "URG", nome: "Rubem Berta", cidade: "Uruguaiana/RS", pais: "Brasil" },
  { iata: "PFB", nome: "Lauro Kortz", cidade: "Passo Fundo/RS", pais: "Brasil" },
  { iata: "SMA", nome: "Santa Maria", cidade: "Santa Maria/RS", pais: "Brasil" },
  { iata: "FLN", nome: "Hercílio Luz", cidade: "Florianópolis/SC", pais: "Brasil" },
  { iata: "NVT", nome: "Ministro Victor Konder", cidade: "Navegantes/SC", pais: "Brasil" },
  { iata: "JOI", nome: "Lauro Carneiro de Loyola", cidade: "Joinville/SC", pais: "Brasil" },
  { iata: "XAP", nome: "Serafin Enoss Bertaso", cidade: "Chapecó/SC", pais: "Brasil" },
  { iata: "CCM", nome: "Diomício Freitas", cidade: "Criciúma/SC", pais: "Brasil" },
  { iata: "CWB", nome: "Afonso Pena", cidade: "Curitiba/PR", pais: "Brasil" },
  { iata: "LDB", nome: "Governador José Richa", cidade: "Londrina/PR", pais: "Brasil" },
  { iata: "MGF", nome: "Silvio Name Júnior", cidade: "Maringá/PR", pais: "Brasil" },
  { iata: "IGU", nome: "Cataratas", cidade: "Foz do Iguaçu/PR", pais: "Brasil" },
  { iata: "CAC", nome: "Adalberto Mendes da Silva", cidade: "Cascavel/PR", pais: "Brasil" },
  { iata: "SSA", nome: "Deputado Luís Eduardo Magalhães", cidade: "Salvador/BA", pais: "Brasil" },
  { iata: "IOS", nome: "Jorge Amado", cidade: "Ilhéus/BA", pais: "Brasil" },
  { iata: "BPS", nome: "Porto Seguro", cidade: "Porto Seguro/BA", pais: "Brasil" },
  { iata: "VDC", nome: "Glauber Rocha", cidade: "Vitória da Conquista/BA", pais: "Brasil" },
  { iata: "LEC", nome: "Coronel Horácio de Mattos", cidade: "Lençóis/BA", pais: "Brasil" },
  { iata: "BRA", nome: "Barreiras", cidade: "Barreiras/BA", pais: "Brasil" },
  { iata: "PAV", nome: "Paulo Afonso", cidade: "Paulo Afonso/BA", pais: "Brasil" },
  { iata: "REC", nome: "Guararapes – Gilberto Freyre", cidade: "Recife/PE", pais: "Brasil" },
  { iata: "PNZ", nome: "Senador Nilo Coelho", cidade: "Petrolina/PE", pais: "Brasil" },
  { iata: "FEN", nome: "Fernando de Noronha", cidade: "Fernando de Noronha/PE", pais: "Brasil" },
  { iata: "FOR", nome: "Pinto Martins", cidade: "Fortaleza/CE", pais: "Brasil" },
  { iata: "JJD", nome: "Comandante Ariston Pessoa", cidade: "Jericoacoara/CE", pais: "Brasil" },
  { iata: "JDO", nome: "Orlando Bezerra de Menezes", cidade: "Juazeiro do Norte/CE", pais: "Brasil" },
  { iata: "NAT", nome: "Aluízio Alves", cidade: "Natal/RN", pais: "Brasil" },
  { iata: "MVF", nome: "Dix-Sept Rosado", cidade: "Mossoró/RN", pais: "Brasil" },
  { iata: "JPA", nome: "Presidente Castro Pinto", cidade: "João Pessoa/PB", pais: "Brasil" },
  { iata: "CPV", nome: "Presidente João Suassuna", cidade: "Campina Grande/PB", pais: "Brasil" },
  { iata: "MCZ", nome: "Zumbi dos Palmares", cidade: "Maceió/AL", pais: "Brasil" },
  { iata: "AJU", nome: "Santa Maria", cidade: "Aracaju/SE", pais: "Brasil" },
  { iata: "THE", nome: "Senador Petrônio Portella", cidade: "Teresina/PI", pais: "Brasil" },
  { iata: "PHB", nome: "Parnaíba", cidade: "Parnaíba/PI", pais: "Brasil" },
  { iata: "SLZ", nome: "Marechal Cunha Machado", cidade: "São Luís/MA", pais: "Brasil" },
  { iata: "IMP", nome: "Prefeito Renato Moreira", cidade: "Imperatriz/MA", pais: "Brasil" },
  { iata: "VIX", nome: "Eurico de Aguiar Salles", cidade: "Vitória/ES", pais: "Brasil" },
  { iata: "SBJ", nome: "São Mateus", cidade: "São Mateus/ES", pais: "Brasil" },
  { iata: "BEL", nome: "Val de Cans", cidade: "Belém/PA", pais: "Brasil" },
  { iata: "STM", nome: "Maestro Wilson Fonseca", cidade: "Santarém/PA", pais: "Brasil" },
  { iata: "MAB", nome: "João Correa da Rocha", cidade: "Marabá/PA", pais: "Brasil" },
  { iata: "ATM", nome: "Altamira", cidade: "Altamira/PA", pais: "Brasil" },
  { iata: "MAO", nome: "Eduardo Gomes", cidade: "Manaus/AM", pais: "Brasil" },
  { iata: "TFF", nome: "Tefé", cidade: "Tefé/AM", pais: "Brasil" },
  { iata: "TBT", nome: "Tabatinga", cidade: "Tabatinga/AM", pais: "Brasil" },
  { iata: "PVH", nome: "Governador Jorge Teixeira", cidade: "Porto Velho/RO", pais: "Brasil" },
  { iata: "RBR", nome: "Plácido de Castro", cidade: "Rio Branco/AC", pais: "Brasil" },
  { iata: "BVB", nome: "Atlas Brasil Cantanhede", cidade: "Boa Vista/RR", pais: "Brasil" },
  { iata: "MCP", nome: "Alberto Alcolumbre", cidade: "Macapá/AP", pais: "Brasil" },
  { iata: "PMW", nome: "Brigadeiro Lysias Rodrigues", cidade: "Palmas/TO", pais: "Brasil" },
  { iata: "CGB", nome: "Marechal Rondon", cidade: "Cuiabá/MT", pais: "Brasil" },
  { iata: "SIN", nome: "Sinop", cidade: "Sinop/MT", pais: "Brasil" },
  { iata: "ROO", nome: "Maestro Marinho Franco", cidade: "Rondonópolis/MT", pais: "Brasil" },
  { iata: "AFL", nome: "Alta Floresta", cidade: "Alta Floresta/MT", pais: "Brasil" },
  { iata: "CGR", nome: "Campo Grande", cidade: "Campo Grande/MS", pais: "Brasil" },
  { iata: "DOU", nome: "Francisco de Matos Pereira", cidade: "Dourados/MS", pais: "Brasil" },
  { iata: "CMG", nome: "Corumbá", cidade: "Corumbá/MS", pais: "Brasil" },
  { iata: "GYN", nome: "Santa Genoveva", cidade: "Goiânia/GO", pais: "Brasil" },
  { iata: "CLV", nome: "Caldas Novas", cidade: "Caldas Novas/GO", pais: "Brasil" },
  { iata: "RAO", nome: "Leite Lopes", cidade: "Ribeirão Preto/SP", pais: "Brasil" },
  { iata: "SJP", nome: "Prof. Eribelto Manoel Reino", cidade: "São José do Rio Preto/SP", pais: "Brasil" },
  { iata: "SJK", nome: "Prof. Urbano Ernesto Stumpf", cidade: "São José dos Campos/SP", pais: "Brasil" },
  { iata: "BAU", nome: "Bauru–Arealva", cidade: "Bauru/SP", pais: "Brasil" },
  { iata: "PPB", nome: "Presidente Prudente", cidade: "Presidente Prudente/SP", pais: "Brasil" },
  { iata: "ARU", nome: "Araçatuba", cidade: "Araçatuba/SP", pais: "Brasil" },
  { iata: "MII", nome: "Frank Miloye Milenkowichi", cidade: "Marília/SP", pais: "Brasil" },
  { iata: "SOD", nome: "Sorocaba", cidade: "Sorocaba/SP", pais: "Brasil" },

  // ── América do Sul ────────────────────────────────────────────────────────
  { iata: "EZE", nome: "Ministro Pistarini – Ezeiza", cidade: "Buenos Aires", pais: "Argentina" },
  { iata: "AEP", nome: "Jorge Newbery", cidade: "Buenos Aires", pais: "Argentina" },
  { iata: "COR", nome: "Ingeniero Taravella", cidade: "Córdoba", pais: "Argentina" },
  { iata: "MVD", nome: "Carrasco", cidade: "Montevidéu", pais: "Uruguai" },
  { iata: "ASU", nome: "Silvio Pettirossi", cidade: "Assunção", pais: "Paraguai" },
  { iata: "SCL", nome: "Arturo Merino Benítez", cidade: "Santiago", pais: "Chile" },
  { iata: "LIM", nome: "Jorge Chávez", cidade: "Lima", pais: "Peru" },
  { iata: "BOG", nome: "El Dorado", cidade: "Bogotá", pais: "Colômbia" },
  { iata: "MDE", nome: "José María Córdova", cidade: "Medellín", pais: "Colômbia" },
  { iata: "CTG", nome: "Rafael Núñez", cidade: "Cartagena", pais: "Colômbia" },
  { iata: "UIO", nome: "Mariscal Sucre", cidade: "Quito", pais: "Equador" },
  { iata: "GYE", nome: "José Joaquín de Olmedo", cidade: "Guayaquil", pais: "Equador" },
  { iata: "CCS", nome: "Simón Bolívar", cidade: "Caracas", pais: "Venezuela" },
  { iata: "VVI", nome: "Viru Viru", cidade: "Santa Cruz de la Sierra", pais: "Bolívia" },
  { iata: "LPB", nome: "El Alto", cidade: "La Paz", pais: "Bolívia" },
  { iata: "GEO", nome: "Cheddi Jagan", cidade: "Georgetown", pais: "Guiana" },
  { iata: "PBM", nome: "Johan Adolf Pengel", cidade: "Paramaribo", pais: "Suriname" },
  { iata: "CAY", nome: "Félix Eboué", cidade: "Caiena", pais: "Guiana Francesa" },

  // ── América do Norte e Central ────────────────────────────────────────────
  { iata: "MIA", nome: "Miami International", cidade: "Miami, FL", pais: "EUA" },
  { iata: "MCO", nome: "Orlando International", cidade: "Orlando, FL", pais: "EUA" },
  { iata: "FLL", nome: "Fort Lauderdale–Hollywood", cidade: "Fort Lauderdale, FL", pais: "EUA" },
  { iata: "JFK", nome: "John F. Kennedy", cidade: "Nova York, NY", pais: "EUA" },
  { iata: "EWR", nome: "Newark Liberty", cidade: "Newark, NJ", pais: "EUA" },
  { iata: "IAH", nome: "George Bush Intercontinental", cidade: "Houston, TX", pais: "EUA" },
  { iata: "HOU", nome: "William P. Hobby", cidade: "Houston, TX", pais: "EUA" },
  { iata: "DFW", nome: "Dallas/Fort Worth", cidade: "Dallas, TX", pais: "EUA" },
  { iata: "ATL", nome: "Hartsfield–Jackson", cidade: "Atlanta, GA", pais: "EUA" },
  { iata: "ORD", nome: "O'Hare", cidade: "Chicago, IL", pais: "EUA" },
  { iata: "LAX", nome: "Los Angeles International", cidade: "Los Angeles, CA", pais: "EUA" },
  { iata: "SFO", nome: "San Francisco International", cidade: "São Francisco, CA", pais: "EUA" },
  { iata: "MSY", nome: "Louis Armstrong", cidade: "Nova Orleans, LA", pais: "EUA" },
  { iata: "IAD", nome: "Washington Dulles", cidade: "Washington, DC", pais: "EUA" },
  { iata: "BOS", nome: "Logan International", cidade: "Boston, MA", pais: "EUA" },
  { iata: "YYZ", nome: "Toronto Pearson", cidade: "Toronto", pais: "Canadá" },
  { iata: "YUL", nome: "Montréal–Trudeau", cidade: "Montreal", pais: "Canadá" },
  { iata: "YVR", nome: "Vancouver International", cidade: "Vancouver", pais: "Canadá" },
  { iata: "YYC", nome: "Calgary International", cidade: "Calgary", pais: "Canadá" },
  { iata: "MEX", nome: "Benito Juárez", cidade: "Cidade do México", pais: "México" },
  { iata: "CUN", nome: "Cancún International", cidade: "Cancún", pais: "México" },
  { iata: "CMN", nome: "Mohammed V", cidade: "Casablanca", pais: "Marrocos" },
  { iata: "PTY", nome: "Tocumen", cidade: "Cidade do Panamá", pais: "Panamá" },
  { iata: "SJO", nome: "Juan Santamaría", cidade: "San José", pais: "Costa Rica" },
  { iata: "HAV", nome: "José Martí", cidade: "Havana", pais: "Cuba" },
  { iata: "SDQ", nome: "Las Américas", cidade: "Santo Domingo", pais: "Rep. Dominicana" },
  { iata: "POS", nome: "Piarco", cidade: "Port of Spain", pais: "Trinidad e Tobago" },

  // ── Europa ────────────────────────────────────────────────────────────────
  { iata: "LIS", nome: "Humberto Delgado", cidade: "Lisboa", pais: "Portugal" },
  { iata: "OPO", nome: "Francisco Sá Carneiro", cidade: "Porto", pais: "Portugal" },
  { iata: "MAD", nome: "Adolfo Suárez Barajas", cidade: "Madri", pais: "Espanha" },
  { iata: "BCN", nome: "El Prat", cidade: "Barcelona", pais: "Espanha" },
  { iata: "CDG", nome: "Charles de Gaulle", cidade: "Paris", pais: "França" },
  { iata: "ORY", nome: "Orly", cidade: "Paris", pais: "França" },
  { iata: "LHR", nome: "Heathrow", cidade: "Londres", pais: "Reino Unido" },
  { iata: "LGW", nome: "Gatwick", cidade: "Londres", pais: "Reino Unido" },
  { iata: "ABZ", nome: "Aberdeen International", cidade: "Aberdeen", pais: "Reino Unido" },
  { iata: "CWL", nome: "Cardiff Airport", cidade: "Cardiff", pais: "Reino Unido" },
  { iata: "AMS", nome: "Schiphol", cidade: "Amsterdã", pais: "Países Baixos" },
  { iata: "FRA", nome: "Frankfurt am Main", cidade: "Frankfurt", pais: "Alemanha" },
  { iata: "MUC", nome: "Franz Josef Strauss", cidade: "Munique", pais: "Alemanha" },
  { iata: "ZRH", nome: "Zurique", cidade: "Zurique", pais: "Suíça" },
  { iata: "GVA", nome: "Genebra", cidade: "Genebra", pais: "Suíça" },
  { iata: "FCO", nome: "Leonardo da Vinci – Fiumicino", cidade: "Roma", pais: "Itália" },
  { iata: "MXP", nome: "Malpensa", cidade: "Milão", pais: "Itália" },
  { iata: "BRU", nome: "Bruxelas", cidade: "Bruxelas", pais: "Bélgica" },
  { iata: "VIE", nome: "Viena", cidade: "Viena", pais: "Áustria" },
  { iata: "CPH", nome: "Kastrup", cidade: "Copenhague", pais: "Dinamarca" },
  { iata: "ARN", nome: "Arlanda", cidade: "Estocolmo", pais: "Suécia" },
  { iata: "OSL", nome: "Gardermoen", cidade: "Oslo", pais: "Noruega" },
  { iata: "SVG", nome: "Stavanger – Sola", cidade: "Stavanger", pais: "Noruega" },
  { iata: "BGO", nome: "Bergen – Flesland", cidade: "Bergen", pais: "Noruega" },
  { iata: "HEL", nome: "Vantaa", cidade: "Helsinque", pais: "Finlândia" },
  { iata: "DUB", nome: "Dublin", cidade: "Dublin", pais: "Irlanda" },
  { iata: "IST", nome: "Istanbul Airport", cidade: "Istambul", pais: "Turquia" },
  { iata: "ATH", nome: "Eleftherios Venizelos", cidade: "Atenas", pais: "Grécia" },
  { iata: "WAW", nome: "Chopin", cidade: "Varsóvia", pais: "Polônia" },
  { iata: "OTP", nome: "Henri Coandă", cidade: "Bucareste", pais: "Romênia" },

  // ── África, Oriente Médio e Ásia-Pacífico ─────────────────────────────────
  { iata: "LAD", nome: "Quatro de Fevereiro", cidade: "Luanda", pais: "Angola" },
  { iata: "MPM", nome: "Maputo", cidade: "Maputo", pais: "Moçambique" },
  { iata: "WDH", nome: "Hosea Kutako International", cidade: "Windhoek", pais: "Namíbia" },
  { iata: "JNB", nome: "O. R. Tambo", cidade: "Joanesburgo", pais: "África do Sul" },
  { iata: "CPT", nome: "Cidade do Cabo", cidade: "Cidade do Cabo", pais: "África do Sul" },
  { iata: "LOS", nome: "Murtala Muhammed", cidade: "Lagos", pais: "Nigéria" },
  { iata: "PHC", nome: "Port Harcourt", cidade: "Port Harcourt", pais: "Nigéria" },
  { iata: "ACC", nome: "Kotoka", cidade: "Acra", pais: "Gana" },
  { iata: "CAI", nome: "Cairo International", cidade: "Cairo", pais: "Egito" },
  { iata: "ADD", nome: "Bole", cidade: "Adis Abeba", pais: "Etiópia" },
  { iata: "NBO", nome: "Jomo Kenyatta", cidade: "Nairóbi", pais: "Quênia" },
  { iata: "SID", nome: "Amílcar Cabral", cidade: "Ilha do Sal", pais: "Cabo Verde" },
  { iata: "DXB", nome: "Dubai International", cidade: "Dubai", pais: "Emirados Árabes" },
  { iata: "AUH", nome: "Abu Dhabi International", cidade: "Abu Dhabi", pais: "Emirados Árabes" },
  { iata: "DOH", nome: "Hamad International", cidade: "Doha", pais: "Catar" },
  { iata: "RUH", nome: "King Khalid", cidade: "Riade", pais: "Arábia Saudita" },
  { iata: "TLV", nome: "Ben Gurion", cidade: "Tel Aviv", pais: "Israel" },
  { iata: "SIN", nome: "Changi", cidade: "Singapura", pais: "Singapura" },
  { iata: "HKG", nome: "Hong Kong International", cidade: "Hong Kong", pais: "China" },
  { iata: "PVG", nome: "Pudong", cidade: "Xangai", pais: "China" },
  { iata: "PEK", nome: "Capital International", cidade: "Pequim", pais: "China" },
  { iata: "NRT", nome: "Narita", cidade: "Tóquio", pais: "Japão" },
  { iata: "HND", nome: "Haneda", cidade: "Tóquio", pais: "Japão" },
  { iata: "ICN", nome: "Incheon", cidade: "Seul", pais: "Coreia do Sul" },
  { iata: "DEL", nome: "Indira Gandhi", cidade: "Nova Délhi", pais: "Índia" },
  { iata: "BOM", nome: "Chhatrapati Shivaji", cidade: "Mumbai", pais: "Índia" },
  { iata: "KUL", nome: "Kuala Lumpur International", cidade: "Kuala Lumpur", pais: "Malásia" },
  { iata: "BKK", nome: "Suvarnabhumi", cidade: "Bangkok", pais: "Tailândia" },
  { iata: "SYD", nome: "Kingsford Smith", cidade: "Sydney", pais: "Austrália" },
  { iata: "PER", nome: "Perth Airport", cidade: "Perth", pais: "Austrália" },
  { iata: "AKL", nome: "Auckland Airport", cidade: "Auckland", pais: "Nova Zelândia" },
];

// Valor gravado no banco (compatível com texto livre já existente).
export function aeroportoLabel(a: Aeroporto): string {
  return `${a.iata} - ${a.cidade}${a.pais === "Brasil" ? "" : ` (${a.pais})`}`;
}

export const AEROPORTO_OPTIONS: string[] = Array.from(
  new Map(AEROPORTOS.map((a) => [aeroportoLabel(a), a])).keys(),
).sort((a, b) => a.localeCompare(b, "pt-BR"));

// Texto de busca — permite achar por IATA, cidade, país ou nome do aeroporto.
export const AEROPORTO_SEARCH: Record<string, string> = Object.fromEntries(
  AEROPORTOS.map((a) => [aeroportoLabel(a), `${a.iata} ${a.nome} ${a.cidade} ${a.pais}`.toLowerCase()]),
);
