import type { DrakeApiReportDefinition, DrakeExecutionParameter } from "./api-report-types";

const report1Parameters: DrakeExecutionParameter[] = [
  {
    operator: "==",
    isPreFilter: false,
    name: "UOP_Embarque",
    columnName: "UOP_Embarque",
    displayText: "Uop de Embarque",
    value: "",
    dbType: "String",
    wellKnowDomain: {
      id: "OPERATIONAL_UNITS",
      name: "OPERATIONAL_UNITS",
      text: null,
      innerValue: {},
    },
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "LogisticaProgramacaoParticipanteCentroCustoCodigo",
    columnName: "LogisticaProgramacaoParticipanteCentroCustoCodigo",
    displayText: "Código do Centro de Custo da Logística de Programação",
    value: "",
    dbType: "String",
    wellKnowDomain: {
      id: "ACTIVED_COST_CENTERS",
      name: "ACTIVED_COST_CENTERS",
      text: null,
      innerValue: {},
    },
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Nome",
    columnName: "Nome",
    displayText: "Nome do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: {
      id: "WORKERS",
      name: "Trabalhadores",
      text: null,
      innerValue: { enum: false },
    },
    multiSelect: true,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "@INI",
    displayText: "Data de Início do Período",
    value: "",
    dbType: "Date",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "@FIM",
    displayText: "Data de Término do Período",
    value: "",
    dbType: "Date",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Empresa",
    columnName: "Empresa",
    displayText: "Empresa do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "FuncaoOperacao",
    columnName: "FuncaoOperacao",
    displayText: "Função de Operação do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: {
      id: "JOBS",
      name: "Funções",
      text: null,
      innerValue: { enum: false },
    },
    multiSelect: true,
  },
];

const report14Parameters: DrakeExecutionParameter[] = [
  {
    operator: "==",
    isPreFilter: false,
    name: "FuncaoFolha",
    columnName: "FuncaoFolha",
    displayText: "Função de Folha do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Nome",
    columnName: "Nome",
    displayText: "Nome do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Matricula",
    columnName: "Matricula",
    displayText: "Matrícula do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "EmpresaNome",
    columnName: "EmpresaNome",
    displayText: "Nome da Empresa do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "@INI",
    displayText: "Data de Início do Período",
    value: "",
    dbType: "Date",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "@FIM",
    displayText: "Data de Término do Período",
    value: "",
    dbType: "Date",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Situacao",
    columnName: "Situacao",
    displayText: "Situação do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Quantidade",
    columnName: "Quantidade",
    displayText: "Quantidade",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "NomeCategoria",
    columnName: "NomeCategoria",
    displayText: "Nome da Categoria do Trabalhador",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: false,
  },
  {
    operator: "==",
    isPreFilter: false,
    name: "Descricao_Evento",
    columnName: "Descricao_Evento",
    displayText: "Descrição do Evento",
    value: "",
    dbType: "String",
    wellKnowDomain: null,
    multiSelect: true,
  },
];

export const API_REPORT_1: DrakeApiReportDefinition = {
  code: 1,
  name: "RELATÓRIO DE EMBARQUE POR CENTRO DE CUSTO",
  queryId: "1ca9b1f3-e25b-ddda-b315-ad5112b51aea",
  queryType: "Deployed",
  outputBaseName: "relatorio-embarque-centro-custo",
  parameterTemplate: report1Parameters,
};

export const API_REPORT_14: DrakeApiReportDefinition = {
  code: 14,
  name: "RELATORIO FUNCIONARIO DISPONIVEL",
  queryId: "911891b7-cbf5-a7fa-a3a0-7cd6593fed95",
  queryType: "Deployed",
  outputBaseName: "relatorio-funcionario-disponivel",
  parameterTemplate: report14Parameters,
};

export const API_REQUIRED_REPORTS: DrakeApiReportDefinition[] = [API_REPORT_1, API_REPORT_14];

/** Code observado nas exportacoes Excel em segundo plano. */
export const BACKGROUND_EXPORT_CODE = 5359;
