/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PmRouteRouteImport } from './routes/pm/route'
import { Route as RhSmsRouteRouteImport } from './routes/rh-sms/route'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminBmRouteImport } from './routes/admin/bm'
import { Route as AdminCollaboratorsRouteImport } from './routes/admin/collaborators'
import { Route as AdminCostSimulatorRouteImport } from './routes/admin/cost-simulator'
import { Route as AdminCostsRouteImport } from './routes/admin/costs'
import { Route as AdminFlowTrackRouteImport } from './routes/admin/flow-track'
import { Route as AdminHistogramaNovoRouteImport } from './routes/admin/histograma-novo'
import { Route as AdminHospedagemRouteImport } from './routes/admin/hospedagem'
import { Route as AdminMaterialsRouteImport } from './routes/admin/materials'
import { Route as AdminNominationsRouteImport } from './routes/admin/nominations'
import { Route as AdminPassagensAereasRouteImport } from './routes/admin/passagens-aereas'
import { Route as AdminPayrollRouteImport } from './routes/admin/payroll'
import { Route as AdminPlanejamentoEmbarqueHistoricoRouteImport } from './routes/admin/planejamento-embarque-historico'
import { Route as AdminRatesRouteImport } from './routes/admin/rates'
import { Route as AdminReembolsosRouteImport } from './routes/admin/reembolsos'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTimesheetOffshoreRouteImport } from './routes/admin/timesheet-offshore'
import { Route as AdminTransportRouteImport } from './routes/admin/transport'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppFinancialRouteImport } from './routes/app/financial'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppTimesheetRouteImport } from './routes/app/timesheet'
import { Route as AppTransportRouteImport } from './routes/app/transport'
import { Route as PmIndexRouteImport } from './routes/pm/index'
import { Route as PmBmsRouteImport } from './routes/pm/bms'
import { Route as RhSmsIndexRouteImport } from './routes/rh-sms/index'
import { Route as ApiPublicLgpFlowMonitoringRouteImport } from './routes/api/public/lgp-flow-monitoring'
import { Route as ApiIntegrationsDrakeQualificationEligibilityRouteImport } from './routes/api/integrations/drake/qualification-eligibility'
import { Route as ApiIntegrationsDrakeQualificationUpdateRouteImport } from './routes/api/integrations/drake/qualification-update'
import { Route as ApiIntegrationsDrakeUpdateRouteImport } from './routes/api/integrations/drake/update'
import { Route as ApiIntegrationsSmsContextRouteImport } from './routes/api/integrations/sms/context'
import { Route as ApiIntegrationsSmsEmployeesRouteImport } from './routes/api/integrations/sms/employees'
import { Route as ApiIntegrationsSmsQualificationsRouteImport } from './routes/api/integrations/sms/qualifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRouteRoute = PmRouteRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const RhSmsRouteRoute = RhSmsRouteRouteImport.update({
  id: '/rh-sms',
  path: '/rh-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBmRoute = AdminBmRouteImport.update({
  id: '/bm',
  path: '/bm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollaboratorsRoute = AdminCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCostSimulatorRoute = AdminCostSimulatorRouteImport.update({
  id: '/cost-simulator',
  path: '/cost-simulator',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCostsRoute = AdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFlowTrackRoute = AdminFlowTrackRouteImport.update({
  id: '/flow-track',
  path: '/flow-track',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHistogramaNovoRoute = AdminHistogramaNovoRouteImport.update({
  id: '/histograma-novo',
  path: '/histograma-novo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHospedagemRoute = AdminHospedagemRouteImport.update({
  id: '/hospedagem',
  path: '/hospedagem',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNominationsRoute = AdminNominationsRouteImport.update({
  id: '/nominations',
  path: '/nominations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPassagensAereasRoute = AdminPassagensAereasRouteImport.update({
  id: '/passagens-aereas',
  path: '/passagens-aereas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlanejamentoEmbarqueHistoricoRoute =
  AdminPlanejamentoEmbarqueHistoricoRouteImport.update({
    id: '/planejamento-embarque-historico',
    path: '/planejamento-embarque-historico',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRatesRoute = AdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReembolsosRoute = AdminReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTimesheetOffshoreRoute = AdminTimesheetOffshoreRouteImport.update({
  id: '/timesheet-offshore',
  path: '/timesheet-offshore',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimesheetRoute = AppTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRouteRoute,
} as any)
const PmIndexRoute = PmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmRouteRoute,
} as any)
const PmBmsRoute = PmBmsRouteImport.update({
  id: '/bms',
  path: '/bms',
  getParentRoute: () => PmRouteRoute,
} as any)
const RhSmsIndexRoute = RhSmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhSmsRouteRoute,
} as any)
const ApiPublicLgpFlowMonitoringRoute =
  ApiPublicLgpFlowMonitoringRouteImport.update({
    id: '/api/public/lgp-flow-monitoring',
    path: '/api/public/lgp-flow-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDrakeQualificationEligibilityRoute =
  ApiIntegrationsDrakeQualificationEligibilityRouteImport.update({
    id: '/api/integrations/drake/qualification-eligibility',
    path: '/api/integrations/drake/qualification-eligibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDrakeQualificationUpdateRoute =
  ApiIntegrationsDrakeQualificationUpdateRouteImport.update({
    id: '/api/integrations/drake/qualification-update',
    path: '/api/integrations/drake/qualification-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDrakeUpdateRoute =
  ApiIntegrationsDrakeUpdateRouteImport.update({
    id: '/api/integrations/drake/update',
    path: '/api/integrations/drake/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSmsContextRoute =
  ApiIntegrationsSmsContextRouteImport.update({
    id: '/api/integrations/sms/context',
    path: '/api/integrations/sms/context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSmsEmployeesRoute =
  ApiIntegrationsSmsEmployeesRouteImport.update({
    id: '/api/integrations/sms/employees',
    path: '/api/integrations/sms/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSmsQualificationsRoute =
  ApiIntegrationsSmsQualificationsRouteImport.update({
    id: '/api/integrations/sms/qualifications',
    path: '/api/integrations/sms/qualifications',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/pm': typeof PmRouteRouteWithChildren
  '/rh-sms': typeof RhSmsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/bm': typeof AdminBmRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/cost-simulator': typeof AdminCostSimulatorRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/flow-track': typeof AdminFlowTrackRoute
  '/admin/histograma-novo': typeof AdminHistogramaNovoRoute
  '/admin/hospedagem': typeof AdminHospedagemRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/passagens-aereas': typeof AdminPassagensAereasRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/planejamento-embarque-historico': typeof AdminPlanejamentoEmbarqueHistoricoRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheet-offshore': typeof AdminTimesheetOffshoreRoute
  '/admin/transport': typeof AdminTransportRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/timesheet': typeof AppTimesheetRoute
  '/app/transport': typeof AppTransportRoute
  '/pm/bms': typeof PmBmsRoute
  '/app/': typeof AppIndexRoute
  '/pm/': typeof PmIndexRoute
  '/rh-sms/': typeof RhSmsIndexRoute
  '/api/public/lgp-flow-monitoring': typeof ApiPublicLgpFlowMonitoringRoute
  '/api/integrations/drake/qualification-eligibility': typeof ApiIntegrationsDrakeQualificationEligibilityRoute
  '/api/integrations/drake/qualification-update': typeof ApiIntegrationsDrakeQualificationUpdateRoute
  '/api/integrations/drake/update': typeof ApiIntegrationsDrakeUpdateRoute
  '/api/integrations/sms/context': typeof ApiIntegrationsSmsContextRoute
  '/api/integrations/sms/employees': typeof ApiIntegrationsSmsEmployeesRoute
  '/api/integrations/sms/qualifications': typeof ApiIntegrationsSmsQualificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/bm': typeof AdminBmRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/cost-simulator': typeof AdminCostSimulatorRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/flow-track': typeof AdminFlowTrackRoute
  '/admin/histograma-novo': typeof AdminHistogramaNovoRoute
  '/admin/hospedagem': typeof AdminHospedagemRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/passagens-aereas': typeof AdminPassagensAereasRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/planejamento-embarque-historico': typeof AdminPlanejamentoEmbarqueHistoricoRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheet-offshore': typeof AdminTimesheetOffshoreRoute
  '/admin/transport': typeof AdminTransportRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/timesheet': typeof AppTimesheetRoute
  '/app/transport': typeof AppTransportRoute
  '/pm/bms': typeof PmBmsRoute
  '/app': typeof AppIndexRoute
  '/pm': typeof PmIndexRoute
  '/rh-sms': typeof RhSmsIndexRoute
  '/api/public/lgp-flow-monitoring': typeof ApiPublicLgpFlowMonitoringRoute
  '/api/integrations/drake/qualification-eligibility': typeof ApiIntegrationsDrakeQualificationEligibilityRoute
  '/api/integrations/drake/qualification-update': typeof ApiIntegrationsDrakeQualificationUpdateRoute
  '/api/integrations/drake/update': typeof ApiIntegrationsDrakeUpdateRoute
  '/api/integrations/sms/context': typeof ApiIntegrationsSmsContextRoute
  '/api/integrations/sms/employees': typeof ApiIntegrationsSmsEmployeesRoute
  '/api/integrations/sms/qualifications': typeof ApiIntegrationsSmsQualificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/pm': typeof PmRouteRouteWithChildren
  '/rh-sms': typeof RhSmsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/bm': typeof AdminBmRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/cost-simulator': typeof AdminCostSimulatorRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/flow-track': typeof AdminFlowTrackRoute
  '/admin/histograma-novo': typeof AdminHistogramaNovoRoute
  '/admin/hospedagem': typeof AdminHospedagemRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/passagens-aereas': typeof AdminPassagensAereasRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/planejamento-embarque-historico': typeof AdminPlanejamentoEmbarqueHistoricoRoute
  '/admin/rates': typeof AdminRatesRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheet-offshore': typeof AdminTimesheetOffshoreRoute
  '/admin/transport': typeof AdminTransportRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/timesheet': typeof AppTimesheetRoute
  '/app/transport': typeof AppTransportRoute
  '/pm/bms': typeof PmBmsRoute
  '/app/': typeof AppIndexRoute
  '/pm/': typeof PmIndexRoute
  '/rh-sms/': typeof RhSmsIndexRoute
  '/api/public/lgp-flow-monitoring': typeof ApiPublicLgpFlowMonitoringRoute
  '/api/integrations/drake/qualification-eligibility': typeof ApiIntegrationsDrakeQualificationEligibilityRoute
  '/api/integrations/drake/qualification-update': typeof ApiIntegrationsDrakeQualificationUpdateRoute
  '/api/integrations/drake/update': typeof ApiIntegrationsDrakeUpdateRoute
  '/api/integrations/sms/context': typeof ApiIntegrationsSmsContextRoute
  '/api/integrations/sms/employees': typeof ApiIntegrationsSmsEmployeesRoute
  '/api/integrations/sms/qualifications': typeof ApiIntegrationsSmsQualificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/pm'
    | '/rh-sms'
    | '/auth'
    | '/pending'
    | '/admin/approvals'
    | '/admin/bm'
    | '/admin/collaborators'
    | '/admin/cost-simulator'
    | '/admin/costs'
    | '/admin/flow-track'
    | '/admin/histograma-novo'
    | '/admin/hospedagem'
    | '/admin/materials'
    | '/admin/nominations'
    | '/admin/passagens-aereas'
    | '/admin/payroll'
    | '/admin/planejamento-embarque-historico'
    | '/admin/rates'
    | '/admin/reembolsos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/timesheet-offshore'
    | '/admin/transport'
    | '/app/documents'
    | '/app/financial'
    | '/app/schedule'
    | '/app/timesheet'
    | '/app/transport'
    | '/pm/bms'
    | '/app/'
    | '/pm/'
    | '/rh-sms/'
    | '/api/public/lgp-flow-monitoring'
    | '/api/integrations/drake/qualification-eligibility'
    | '/api/integrations/drake/qualification-update'
    | '/api/integrations/drake/update'
    | '/api/integrations/sms/context'
    | '/api/integrations/sms/employees'
    | '/api/integrations/sms/qualifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/pending'
    | '/admin/approvals'
    | '/admin/bm'
    | '/admin/collaborators'
    | '/admin/cost-simulator'
    | '/admin/costs'
    | '/admin/flow-track'
    | '/admin/histograma-novo'
    | '/admin/hospedagem'
    | '/admin/materials'
    | '/admin/nominations'
    | '/admin/passagens-aereas'
    | '/admin/payroll'
    | '/admin/planejamento-embarque-historico'
    | '/admin/rates'
    | '/admin/reembolsos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/timesheet-offshore'
    | '/admin/transport'
    | '/app/documents'
    | '/app/financial'
    | '/app/schedule'
    | '/app/timesheet'
    | '/app/transport'
    | '/pm/bms'
    | '/app'
    | '/pm'
    | '/rh-sms'
    | '/api/public/lgp-flow-monitoring'
    | '/api/integrations/drake/qualification-eligibility'
    | '/api/integrations/drake/qualification-update'
    | '/api/integrations/drake/update'
    | '/api/integrations/sms/context'
    | '/api/integrations/sms/employees'
    | '/api/integrations/sms/qualifications'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/pm'
    | '/rh-sms'
    | '/auth'
    | '/pending'
    | '/admin/approvals'
    | '/admin/bm'
    | '/admin/collaborators'
    | '/admin/cost-simulator'
    | '/admin/costs'
    | '/admin/flow-track'
    | '/admin/histograma-novo'
    | '/admin/hospedagem'
    | '/admin/materials'
    | '/admin/nominations'
    | '/admin/passagens-aereas'
    | '/admin/payroll'
    | '/admin/planejamento-embarque-historico'
    | '/admin/rates'
    | '/admin/reembolsos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/timesheet-offshore'
    | '/admin/transport'
    | '/app/documents'
    | '/app/financial'
    | '/app/schedule'
    | '/app/timesheet'
    | '/app/transport'
    | '/pm/bms'
    | '/app/'
    | '/pm/'
    | '/rh-sms/'
    | '/api/public/lgp-flow-monitoring'
    | '/api/integrations/drake/qualification-eligibility'
    | '/api/integrations/drake/qualification-update'
    | '/api/integrations/drake/update'
    | '/api/integrations/sms/context'
    | '/api/integrations/sms/employees'
    | '/api/integrations/sms/qualifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PmRouteRoute: typeof PmRouteRouteWithChildren
  RhSmsRouteRoute: typeof RhSmsRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  ApiPublicLgpFlowMonitoringRoute: typeof ApiPublicLgpFlowMonitoringRoute
  ApiIntegrationsDrakeQualificationEligibilityRoute: typeof ApiIntegrationsDrakeQualificationEligibilityRoute
  ApiIntegrationsDrakeQualificationUpdateRoute: typeof ApiIntegrationsDrakeQualificationUpdateRoute
  ApiIntegrationsDrakeUpdateRoute: typeof ApiIntegrationsDrakeUpdateRoute
  ApiIntegrationsSmsContextRoute: typeof ApiIntegrationsSmsContextRoute
  ApiIntegrationsSmsEmployeesRoute: typeof ApiIntegrationsSmsEmployeesRoute
  ApiIntegrationsSmsQualificationsRoute: typeof ApiIntegrationsSmsQualificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh-sms': {
      id: '/rh-sms'
      path: '/rh-sms'
      fullPath: '/rh-sms'
      preLoaderRoute: typeof RhSmsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bm': {
      id: '/admin/bm'
      path: '/bm'
      fullPath: '/admin/bm'
      preLoaderRoute: typeof AdminBmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collaborators': {
      id: '/admin/collaborators'
      path: '/collaborators'
      fullPath: '/admin/collaborators'
      preLoaderRoute: typeof AdminCollaboratorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cost-simulator': {
      id: '/admin/cost-simulator'
      path: '/cost-simulator'
      fullPath: '/admin/cost-simulator'
      preLoaderRoute: typeof AdminCostSimulatorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/costs': {
      id: '/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminCostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/flow-track': {
      id: '/admin/flow-track'
      path: '/flow-track'
      fullPath: '/admin/flow-track'
      preLoaderRoute: typeof AdminFlowTrackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/histograma-novo': {
      id: '/admin/histograma-novo'
      path: '/histograma-novo'
      fullPath: '/admin/histograma-novo'
      preLoaderRoute: typeof AdminHistogramaNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hospedagem': {
      id: '/admin/hospedagem'
      path: '/hospedagem'
      fullPath: '/admin/hospedagem'
      preLoaderRoute: typeof AdminHospedagemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nominations': {
      id: '/admin/nominations'
      path: '/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminNominationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/passagens-aereas': {
      id: '/admin/passagens-aereas'
      path: '/passagens-aereas'
      fullPath: '/admin/passagens-aereas'
      preLoaderRoute: typeof AdminPassagensAereasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/planejamento-embarque-historico': {
      id: '/admin/planejamento-embarque-historico'
      path: '/planejamento-embarque-historico'
      fullPath: '/admin/planejamento-embarque-historico'
      preLoaderRoute: typeof AdminPlanejamentoEmbarqueHistoricoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rates': {
      id: '/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AdminRatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reembolsos': {
      id: '/admin/reembolsos'
      path: '/reembolsos'
      fullPath: '/admin/reembolsos'
      preLoaderRoute: typeof AdminReembolsosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/timesheet-offshore': {
      id: '/admin/timesheet-offshore'
      path: '/timesheet-offshore'
      fullPath: '/admin/timesheet-offshore'
      preLoaderRoute: typeof AdminTimesheetOffshoreRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/financial': {
      id: '/app/financial'
      path: '/financial'
      fullPath: '/app/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/timesheet': {
      id: '/app/timesheet'
      path: '/timesheet'
      fullPath: '/app/timesheet'
      preLoaderRoute: typeof AppTimesheetRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transport': {
      id: '/app/transport'
      path: '/transport'
      fullPath: '/app/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/pm/': {
      id: '/pm/'
      path: '/'
      fullPath: '/pm/'
      preLoaderRoute: typeof PmIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/pm/bms': {
      id: '/pm/bms'
      path: '/bms'
      fullPath: '/pm/bms'
      preLoaderRoute: typeof PmBmsRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/rh-sms/': {
      id: '/rh-sms/'
      path: '/'
      fullPath: '/rh-sms/'
      preLoaderRoute: typeof RhSmsIndexRouteImport
      parentRoute: typeof RhSmsRouteRoute
    }
    '/api/public/lgp-flow-monitoring': {
      id: '/api/public/lgp-flow-monitoring'
      path: '/api/public/lgp-flow-monitoring'
      fullPath: '/api/public/lgp-flow-monitoring'
      preLoaderRoute: typeof ApiPublicLgpFlowMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/drake/qualification-eligibility': {
      id: '/api/integrations/drake/qualification-eligibility'
      path: '/api/integrations/drake/qualification-eligibility'
      fullPath: '/api/integrations/drake/qualification-eligibility'
      preLoaderRoute: typeof ApiIntegrationsDrakeQualificationEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/drake/qualification-update': {
      id: '/api/integrations/drake/qualification-update'
      path: '/api/integrations/drake/qualification-update'
      fullPath: '/api/integrations/drake/qualification-update'
      preLoaderRoute: typeof ApiIntegrationsDrakeQualificationUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/drake/update': {
      id: '/api/integrations/drake/update'
      path: '/api/integrations/drake/update'
      fullPath: '/api/integrations/drake/update'
      preLoaderRoute: typeof ApiIntegrationsDrakeUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/sms/context': {
      id: '/api/integrations/sms/context'
      path: '/api/integrations/sms/context'
      fullPath: '/api/integrations/sms/context'
      preLoaderRoute: typeof ApiIntegrationsSmsContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/sms/employees': {
      id: '/api/integrations/sms/employees'
      path: '/api/integrations/sms/employees'
      fullPath: '/api/integrations/sms/employees'
      preLoaderRoute: typeof ApiIntegrationsSmsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/sms/qualifications': {
      id: '/api/integrations/sms/qualifications'
      path: '/api/integrations/sms/qualifications'
      fullPath: '/api/integrations/sms/qualifications'
      preLoaderRoute: typeof ApiIntegrationsSmsQualificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBmRoute: typeof AdminBmRoute
  AdminCollaboratorsRoute: typeof AdminCollaboratorsRoute
  AdminCostSimulatorRoute: typeof AdminCostSimulatorRoute
  AdminCostsRoute: typeof AdminCostsRoute
  AdminFlowTrackRoute: typeof AdminFlowTrackRoute
  AdminHistogramaNovoRoute: typeof AdminHistogramaNovoRoute
  AdminHospedagemRoute: typeof AdminHospedagemRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminNominationsRoute: typeof AdminNominationsRoute
  AdminPassagensAereasRoute: typeof AdminPassagensAereasRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminPlanejamentoEmbarqueHistoricoRoute: typeof AdminPlanejamentoEmbarqueHistoricoRoute
  AdminRatesRoute: typeof AdminRatesRoute
  AdminReembolsosRoute: typeof AdminReembolsosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTimesheetOffshoreRoute: typeof AdminTimesheetOffshoreRoute
  AdminTransportRoute: typeof AdminTransportRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBmRoute: AdminBmRoute,
  AdminCollaboratorsRoute: AdminCollaboratorsRoute,
  AdminCostSimulatorRoute: AdminCostSimulatorRoute,
  AdminCostsRoute: AdminCostsRoute,
  AdminFlowTrackRoute: AdminFlowTrackRoute,
  AdminHistogramaNovoRoute: AdminHistogramaNovoRoute,
  AdminHospedagemRoute: AdminHospedagemRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminNominationsRoute: AdminNominationsRoute,
  AdminPassagensAereasRoute: AdminPassagensAereasRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminPlanejamentoEmbarqueHistoricoRoute:
    AdminPlanejamentoEmbarqueHistoricoRoute,
  AdminRatesRoute: AdminRatesRoute,
  AdminReembolsosRoute: AdminReembolsosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTimesheetOffshoreRoute: AdminTimesheetOffshoreRoute,
  AdminTransportRoute: AdminTransportRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinancialRoute: typeof AppFinancialRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppTimesheetRoute: typeof AppTimesheetRoute
  AppTransportRoute: typeof AppTransportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinancialRoute: AppFinancialRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppTimesheetRoute: AppTimesheetRoute,
  AppTransportRoute: AppTransportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PmRouteRouteChildren {
  PmBmsRoute: typeof PmBmsRoute
  PmIndexRoute: typeof PmIndexRoute
}

const PmRouteRouteChildren: PmRouteRouteChildren = {
  PmBmsRoute: PmBmsRoute,
  PmIndexRoute: PmIndexRoute,
}

const PmRouteRouteWithChildren =
  PmRouteRoute._addFileChildren(PmRouteRouteChildren)

interface RhSmsRouteRouteChildren {
  RhSmsIndexRoute: typeof RhSmsIndexRoute
}

const RhSmsRouteRouteChildren: RhSmsRouteRouteChildren = {
  RhSmsIndexRoute: RhSmsIndexRoute,
}

const RhSmsRouteRouteWithChildren = RhSmsRouteRoute._addFileChildren(
  RhSmsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  PmRouteRoute: PmRouteRouteWithChildren,
  RhSmsRouteRoute: RhSmsRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  ApiPublicLgpFlowMonitoringRoute: ApiPublicLgpFlowMonitoringRoute,
  ApiIntegrationsDrakeQualificationEligibilityRoute:
    ApiIntegrationsDrakeQualificationEligibilityRoute,
  ApiIntegrationsDrakeQualificationUpdateRoute:
    ApiIntegrationsDrakeQualificationUpdateRoute,
  ApiIntegrationsDrakeUpdateRoute: ApiIntegrationsDrakeUpdateRoute,
  ApiIntegrationsSmsContextRoute: ApiIntegrationsSmsContextRoute,
  ApiIntegrationsSmsEmployeesRoute: ApiIntegrationsSmsEmployeesRoute,
  ApiIntegrationsSmsQualificationsRoute: ApiIntegrationsSmsQualificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
