/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PmRouteRouteImport } from './routes/pm/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PmIndexRouteImport } from './routes/pm/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppTransportRouteImport } from './routes/app/transport'
import { Route as AppTimesheetRouteImport } from './routes/app/timesheet'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppFinancialRouteImport } from './routes/app/financial'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AdminTransportRouteImport } from './routes/admin/transport'
import { Route as AdminTimesheetsRouteImport } from './routes/admin/timesheets'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPayrollRouteImport } from './routes/admin/payroll'
import { Route as AdminNominationsRouteImport } from './routes/admin/nominations'
import { Route as AdminMaterialsRouteImport } from './routes/admin/materials'
import { Route as AdminHotelRouteImport } from './routes/admin/hotel'
import { Route as AdminEmbarkationsRouteImport } from './routes/admin/embarkations'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminCostsRouteImport } from './routes/admin/costs'
import { Route as AdminCollaboratorsRouteImport } from './routes/admin/collaborators'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRouteRoute = PmRouteRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PmIndexRoute = PmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimesheetRoute = AppTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNominationsRoute = AdminNominationsRouteImport.update({
  id: '/nominations',
  path: '/nominations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHotelRoute = AdminHotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmbarkationsRoute = AdminEmbarkationsRouteImport.update({
  id: '/embarkations',
  path: '/embarkations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCostsRoute = AdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollaboratorsRoute = AdminCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/pm': typeof PmRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/embarkations': typeof AdminEmbarkationsRoute
  '/admin/hotel': typeof AdminHotelRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/timesheet': typeof AppTimesheetRoute
  '/app/transport': typeof AppTransportRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/pm/': typeof PmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/embarkations': typeof AdminEmbarkationsRoute
  '/admin/hotel': typeof AdminHotelRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/timesheet': typeof AppTimesheetRoute
  '/app/transport': typeof AppTransportRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/pm': typeof PmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/pm': typeof PmRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/embarkations': typeof AdminEmbarkationsRoute
  '/admin/hotel': typeof AdminHotelRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/financial': typeof AppFinancialRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/timesheet': typeof AppTimesheetRoute
  '/app/transport': typeof AppTransportRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/pm/': typeof PmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/pm'
    | '/auth'
    | '/pending'
    | '/admin/approvals'
    | '/admin/collaborators'
    | '/admin/costs'
    | '/admin/documents'
    | '/admin/embarkations'
    | '/admin/hotel'
    | '/admin/materials'
    | '/admin/nominations'
    | '/admin/payroll'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/timesheets'
    | '/admin/transport'
    | '/app/documents'
    | '/app/financial'
    | '/app/schedule'
    | '/app/timesheet'
    | '/app/transport'
    | '/admin/'
    | '/app/'
    | '/pm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/admin/approvals'
    | '/admin/collaborators'
    | '/admin/costs'
    | '/admin/documents'
    | '/admin/embarkations'
    | '/admin/hotel'
    | '/admin/materials'
    | '/admin/nominations'
    | '/admin/payroll'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/timesheets'
    | '/admin/transport'
    | '/app/documents'
    | '/app/financial'
    | '/app/schedule'
    | '/app/timesheet'
    | '/app/transport'
    | '/admin'
    | '/app'
    | '/pm'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/pm'
    | '/auth'
    | '/pending'
    | '/admin/approvals'
    | '/admin/collaborators'
    | '/admin/costs'
    | '/admin/documents'
    | '/admin/embarkations'
    | '/admin/hotel'
    | '/admin/materials'
    | '/admin/nominations'
    | '/admin/payroll'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/timesheets'
    | '/admin/transport'
    | '/app/documents'
    | '/app/financial'
    | '/app/schedule'
    | '/app/timesheet'
    | '/app/transport'
    | '/admin/'
    | '/app/'
    | '/pm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PmRouteRoute: typeof PmRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm/': {
      id: '/pm/'
      path: '/'
      fullPath: '/pm/'
      preLoaderRoute: typeof PmIndexRouteImport
      parentRoute: typeof PmRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/transport': {
      id: '/app/transport'
      path: '/transport'
      fullPath: '/app/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/timesheet': {
      id: '/app/timesheet'
      path: '/timesheet'
      fullPath: '/app/timesheet'
      preLoaderRoute: typeof AppTimesheetRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/financial': {
      id: '/app/financial'
      path: '/financial'
      fullPath: '/app/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nominations': {
      id: '/admin/nominations'
      path: '/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminNominationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hotel': {
      id: '/admin/hotel'
      path: '/hotel'
      fullPath: '/admin/hotel'
      preLoaderRoute: typeof AdminHotelRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/embarkations': {
      id: '/admin/embarkations'
      path: '/embarkations'
      fullPath: '/admin/embarkations'
      preLoaderRoute: typeof AdminEmbarkationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/costs': {
      id: '/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminCostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collaborators': {
      id: '/admin/collaborators'
      path: '/collaborators'
      fullPath: '/admin/collaborators'
      preLoaderRoute: typeof AdminCollaboratorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminCollaboratorsRoute: typeof AdminCollaboratorsRoute
  AdminCostsRoute: typeof AdminCostsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEmbarkationsRoute: typeof AdminEmbarkationsRoute
  AdminHotelRoute: typeof AdminHotelRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminNominationsRoute: typeof AdminNominationsRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRoute
  AdminTransportRoute: typeof AdminTransportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminCollaboratorsRoute: AdminCollaboratorsRoute,
  AdminCostsRoute: AdminCostsRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEmbarkationsRoute: AdminEmbarkationsRoute,
  AdminHotelRoute: AdminHotelRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminNominationsRoute: AdminNominationsRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTimesheetsRoute: AdminTimesheetsRoute,
  AdminTransportRoute: AdminTransportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinancialRoute: typeof AppFinancialRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppTimesheetRoute: typeof AppTimesheetRoute
  AppTransportRoute: typeof AppTransportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinancialRoute: AppFinancialRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppTimesheetRoute: AppTimesheetRoute,
  AppTransportRoute: AppTransportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PmRouteRouteChildren {
  PmIndexRoute: typeof PmIndexRoute
}

const PmRouteRouteChildren: PmRouteRouteChildren = {
  PmIndexRoute: PmIndexRoute,
}

const PmRouteRouteWithChildren =
  PmRouteRoute._addFileChildren(PmRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  PmRouteRoute: PmRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
